### ISSUE TITLE
Supla::Html::SelectCmdInputParameter + save

### ISSUE THREAD

**Issue by radzikr** [SUPLA/supla-device#39]
Supla::Html::SelectCmdInputParameter + save

prośba o dodanie:
pole Supla::Html::SelectCmdInputParameter z możliwością zapamiętania wyboru, by po wczytaniu pamiętało wybór jak w statusie led

**Comment by klew** [comment]
@radzikr ten input jest do uruchamiania komend.
Gdy nie chciałbyś raczej zwykłego selecta gdzie można ustawić jakie opcje są do wyboru? Analogicznie jak jest status LED?

**Comment by radzikr** [comment]
Może napisze co bym potrzebował.
Potrzebuje selektor z pamięcią, za pomocą którego mogę zrobić wybór GPIO.

Nie wiem czy w dobrym kierunku uderzam.
