### ISSUE TITLE
arduino 1.8.19 error complilation

### ISSUE THREAD

**Issue by wchpikus** [SUPLA/supla-device#72]
example from lib, esp8266.

In file included from ......\Documents\Arduino\test-supla\test-supla.ino:40:0:
....\Documents\Arduino\libraries\supla-device-main\src/supla/network/esp_wifi.h: In member function 'virtual void Supla::ESPWifi::setup()':
......Documents\Arduino\libraries\supla-device-main\src/supla/network/esp_wifi.h:72:12: error: 'class ESP8266WiFiClass' has no member named 'setHostname'
       WiFi.setHostname(hostname);
            ^
.....\Documents\Arduino\libraries\supla-device-main\src/supla/network/esp_wifi.h:125:12: error: 'class ESP8266WiFiClass' has no member named 'setHostname'
       WiFi.setHostname(hostname);
any suggestion?

**Comment by klew** [comment]
Probably you have too old boards for esp
